# Generated by Django 5.2.6 on 2025-10-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(max_length=64, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='Available', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuzzJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('format_error', '형식 오류'), ('logic_error', '논리 오류'), ('order_disrupt', '순서 교란'), ('timing_mutate', '타이밍 변조')], max_length=32)),
                ('status', models.CharField(default='idle', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('action', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(blank=True, max_length=64, null=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.chargepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.IntegerField(default=1)),
                ('transaction_id', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('meter_start', models.IntegerField(default=0)),
                ('meter_stop', models.IntegerField(blank=True, null=True)),
                ('energy_Wh', models.FloatField(blank=True, null=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.chargepoint')),
            ],
            options={
                'unique_together': {('cp', 'transaction_id')},
            },
        ),
        migrations.CreateModel(
            name='MeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('power_W', models.FloatField(blank=True, null=True)),
                ('energy_Wh', models.FloatField(blank=True, null=True)),
                ('current_A', models.FloatField(blank=True, null=True)),
                ('voltage_V', models.FloatField(blank=True, null=True)),
                ('soc_percent', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='core.chargepoint')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_values', to='core.transaction')),
            ],
        ),
    ]
