# Generated by Django 5.2.6 on 2025-10-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chargepoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fuzzjob',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='metervalue',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='cp_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargepoint'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='direction',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuzzjob',
            name='scenario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fuzzjob',
            name='status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='metervalue',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargepoint'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargepoint'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=1),
        ),
    ]
