# Generated by Django 5.2.6 on 2025-11-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_controlcommand_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcommand',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('done', 'done'), ('error', 'error')], default='queued', max_length=16),
        ),
    ]
